(executable
 (name toplevel)
 (modes wasm)
 (libraries
   js_of_ocaml
   js_of_ocaml-toplevel.common
   compiler-libs.toplevel
   wasm_of_ocaml-compiler.dynlink)
 (preprocess (pps js_of_ocaml-ppx))
 (link_flags (:standard -linkall -g))
 (wasm_of_ocaml
   (flags
     :standard
     --toplevel
     --disable=effects)))
